### ISSUE TITLE
插件中文显示乱码

### ISSUE THREAD

**Issue by 1th0n** [z1un/Z1-AggressorScripts#2]
cs4.3版本插件装上去之后中文显示乱码，且显示顺序与您截图顺序也不一样，请问这要如何解决？
对.aggressor.prop添加client.font.font=Microsoft-YaHei-UI 10也没用~
![image](https://user-images.githubusercontent.com/34960993/124057935-fbb83f80-da5a-11eb-8c9c-6b5c024bc7cf.png)

**Comment by z1un** [comment]
> cs4.3版本插件装上去之后中文显示乱码，且显示顺序与您截图顺序也不一样，请问这要如何解决？
> 对.aggressor.prop添加client.font.font=Microsoft-YaHei-UI 10也没用~
> ![image](https://user-images.githubusercontent.com/34960993/124057935-fbb83f80-da5a-11eb-8c9c-6b5c024bc7cf.png)

请确保cs启动参数设置字符格式为utf-8，其次图片上面只是第一个版本，目前已经几次更新
